---
title: "How to use the GoogleImage2Array functions"
author: 
- name: Satoshi Kume
  email: satoshi.kume.1984@gmail.com
date: "`r Sys.Date()`"
graphics: no
package: GoogleImage2Array
output:
    BiocStyle::html_document:
        toc_float: false
vignette: >
    %\VignetteIndexEntry{How to use GoogleImage2array}
    %\VignetteIndexEntry{GoogleImage2Array}
    %\VignetteEncoding{UTF-8}
    %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r style, echo = FALSE, results = 'asis', message=FALSE}
BiocStyle::markdown()
```

**Last modified:** `r file.info("HowToUse.Rmd")$mtime`<br />
**Compiled**: `r date()`

# Load packages

```{r echo=TRUE, eval=FALSE}
library(GoogleImage2Array)
```

# Get images via Google Image Search

`GoogleImage2array` function provide an array of images via google image search.

```{r echo=TRUE, eval=FALSE}
#Search by persian cat
query <- "persian cat"
CatImg <- GoogleImage2array(query)

#show info
str(CatImg)
#List of 2
# $ array: num [1:20, 1:64, 1:64, 1:3] 0.0141 0.7608 0.111 0.7067 0.3398 ...
# $ query: chr "persian cat"

#Search by Shiba inu
query <- "Shiba inu"
DogImg <- GoogleImage2array(query)

#show info
str(DogImg)
#List of 2
# $ array: num [1:20, 1:64, 1:64, 1:3] 0.1667 0.0689 0.9373 0.3808 0.3851 ...
# $ query: chr "Shiba inu"

#Bind arrays
ImgDat <- bind.array(CatImg, DogImg)

#show info
str(ImgDat)

```

# Display images

`display.array` show a result as a tiled image.

```{r echo=TRUE, eval=FALSE}
#show CatImg
display.array(CatImg)

#show DogImg
display.array(DogImg)

```

# Download & display images

```{r echo=TRUE, eval=FALSE}
#search Shiba inu & display the images
display.array(GoogleImage2array("Shiba inu"))
```

# Session information {.unnumbered}
```{r sessionInfo, echo=FALSE}
sessionInfo()
```
